kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
# patch it further using a JSON 6902 patch
#kubeadmConfigPatchesJSON6902:
#- group: kubeadm.k8s.io
#  version: v1beta2
#  kind: ClusterConfiguration
#  patch: |
#    - op: add
#      path: /traefik-certs
#      value: localhost
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 31000
    hostPort: 8081
- role: worker
  extraPortMappings:
  - containerPort: 31001
    hostPort: 8082
- role: worker
  extraPortMappings:
  - containerPort: 31002
    hostPort: 8083